### ISSUE TITLE
Additional details

### ISSUE THREAD

**Issue by Scheevel** [OneNoteDev/OneNoteAPIPostmanCollection#1]
The README.md doesn't provide explicit instruction of how to obtain Client ID. Could you elaborate on how/where to obtain the Client Id?  Thank you.

**Comment by An631** [comment]
Resolved in latest commit. 
Added [a link to documentation](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/how-to/onenote-auth#register-your-application-and-get-a-client-id-and-secret-consumer-apps) of how to obtain a clientId.
